pdf_my_site_front_homepage:
    path:     /
    defaults: { _controller: PdfMySiteFrontBundle:Default:index }
    options:
        sitemap: true
    
pdf_my_site_front_generate:
    path:     /generate
    defaults: { _controller: PdfMySiteFrontBundle:Default:generate }
    options:
        expose: true
        
pdf_my_site_front_archives:
    path:     /archives/{page}
    defaults: { _controller: PdfMySiteFrontBundle:Default:archives, page: 1}
    requirements:
        page:  \d+
    options:
        sitemap: true
