pdf_my_site_front_homepage:
    path:     /
    defaults: { _controller: PdfMySiteFrontBundle:Default:index }
    
pdf_my_site_front_generate:
    path:     /generate
    defaults: { _controller: PdfMySiteFrontBundle:Default:generate }
