<?php

namespace PdfMySite\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArchivesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivesRepository extends EntityRepository
{
}
